### Get infos set à rien

### Get Roles
GET http://localhost:3000/informations/status


### Get abonnement
GET http://localhost:3000/informations/abonnement


### Get genres
GET http://localhost:3000/informations/genres
